format = "JSON" # ZQL | JSON

# compression -> gzip | xz | lzma | zstd
# bundle -> combine persisted data into single archive ideal for backups and migration
# filename -> name of the archive ( prefix if not bundle)
[persistence]
enable = true

[branch]
merge_mode = "overwrite" # no_overwrite | overwrite | overwrite_partial | swap

[accounts]
default = "guest"
[accounts.password]
min_length = 8
max_length = 32

[communication]
[communication.ip]
enable = true
port = 6748
